services:
  proxy:
    image: nginx:1.27.2-alpine
    container_name: ligevan-proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - '3000:3000'
      - '8080:8080'
      - '9000:9000'
    networks:
      - ligevan-network

  ligevan-backend:
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mongodb://ligevan-database:27017/ligevan
      - JWT_SECRET=your-secret
      - JWT_EXPIRES=2h
      - GOOGLE_OAUTH2_CLIENT_ID=abcxyz
      - GOOGLE_OAUTH2_CLIENT_SECRET=secret-key
      - GOOGLE_OAUTH2_CLIENT_CALLBACK=http://localhost:3000/api/auth/student/callback
      - ALLOWED_ORIGINS=http://ligevan-frontend:8080,http://localhost:3000,https://localhost:3001
      - FRONTEND_URL=http://ligevan-frontend:8080

  ligevan-frontend:
    environment:
      - VITE_BACKEND_URL=http://ligevan-backend:3000
