name: Build backend

on:
  push:
    paths:
      - backend/**

jobs:
  build:
    name: Build backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: |
          cd backend
          yarn

      - name: Build backend
        run: |
          cd backend
          yarn build
