name: Publish frontend image

on:
  push:
    branches:
      - main
    paths:
      - frontend/**

jobs:
  publish:
    name: Publish frontend image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version
        id: get_version
        run: |
          sudo apt-get install jq
          chmod +x ./scripts/get-version.sh
          echo "version=$(./scripts/get-version.sh ./frontend/package.json)" >> $GITHUB_OUTPUT

      - name: Login ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish frontend image
        run: |
          cd frontend
          docker buildx build . \
            -t ghcr.io/${{ github.repository_owner }}/ligevan-frontend:${{ steps.get_version.outputs.version }} \
            -t ghcr.io/${{ github.repository_owner }}/ligevan-frontend:latest \
            --platform=linux/amd64 \
            --load
          docker push ghcr.io/${{ github.repository_owner }}/ligevan-frontend:${{ steps.get_version.outputs.version }}
          docker push ghcr.io/${{ github.repository_owner }}/ligevan-frontend:latest
