name: Publish backend image

on:
  workflow_run:
    workflows: [Build backend]
    types:
      - completed
    branches:
      - main
    paths:
      - backend/**

jobs:
  publish:
    name: Publish backend image
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version
        id: get_version
        run: |
          sudo apt-get install jq
          chmod +x ./scripts/get-version.sh
          echo "version=$(./scripts/get-version.sh ./backend/package.json)" >> $GITHUB_OUTPUT

      - name: Login ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish backend image
        run: |
          cd backend
          docker buildx build . \
            -t ghcr.io/${{ github.repository_owner }}/ligevan-backend:${{ steps.get_version.outputs.version }} \
            -t ghcr.io/${{ github.repository_owner }}/ligevan-backend:latest \
            --platform=linux/amd64 \
            --load
          docker push ghcr.io/${{ github.repository_owner }}/ligevan-backend:${{ steps.get_version.outputs.version }}
          docker push ghcr.io/${{ github.repository_owner }}/ligevan-backend:latest
